name = "jasonkuhrt-website"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".svelte-kit/cloudflare"

# Cloudflare Pages configuration
[env.production]
name = "jasonkuhrt-website"

[env.preview]
name = "jasonkuhrt-website-preview"
