name = "website"
compatibility_date = "2024-01-01"

pages_build_output_dir = "build/client"

# Cloudflare Pages configuration
[env.production]
name = "website"

[env.preview]
name = "website-preview"
